apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: karaokehub
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cloudsql-instances: heroic-footing-460117-k8:us-central1:accountant
    spec:
      containerConcurrency: 10
      timeoutSeconds: 900
      serviceAccountName: 203453576607-compute@developer.gserviceaccount.com
      containers:
        - image: gcr.io/heroic-footing-460117-k8/karaokehub:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
          env:
            # Application Configuration
            - name: NODE_ENV
              value: 'production'
            - name: NODE_OPTIONS
              value: '--max-old-space-size=1536'
            
            # URL Configuration
            - name: FRONTEND_URL
              value: 'https://karaoke-hub.com'
            - name: BACKEND_URL
              value: 'https://karaoke-hub.com'
            - name: ALLOWED_ORIGINS
              value: 'https://karaoke-hub.com'
            
            # Database Configuration (Production Cloud SQL)
            - name: DATABASE_SOCKET_PATH
              value: '/cloudsql/heroic-footing-460117-k8:us-central1:accountant'
            - name: DATABASE_NAME
              value: 'karaoke-hub'
            - name: DATABASE_SYNCHRONIZE
              value: 'false'
            
            # Production Features
            - name: PRODUCTION_UPLOAD_TOKEN
              value: 'karaoke-hub-data-integration-system'
            
            # Puppeteer Configuration
            - name: PUPPETEER_EXECUTABLE_PATH
              value: '/usr/bin/chromium-browser'
            
            # Stripe Configuration (Product IDs - not sensitive)
            - name: STRIPE_AD_FREE_PRICE_ID
              value: 'price_1S08ls2lgQyeTycPCNCNAdxD'
            - name: STRIPE_PREMIUM_PRICE_ID
              value: 'price_1S08lu2lgQyeTycPfKtS3gAp'
            
            # iTunes API Configuration
            - name: ITUNES_API_BASE_URL
              value: 'https://itunes.apple.com'
            # Database Credentials (Secrets)
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_DB_USERNAME
                  key: latest
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_DB_PASSWORD
                  key: latest
            
            # JWT Secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_JWT_SECRET
                  key: latest
            
            # Google OAuth Credentials (Secrets)
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_GOOGLE_CLIENT_ID
                  key: latest
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_GOOGLE_CLIENT_SECRET
                  key: latest
            
            # Google Maps API Keys (Secrets)
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_GOOGLE_MAPS_API_KEY
                  key: latest
            
            # Facebook OAuth Credentials (Secrets)
            - name: FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_FACEBOOK_APP_ID
                  key: latest
            - name: FACEBOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_FACEBOOK_APP_SECRET
                  key: latest
            - name: FACEBOOK_PARSER_APP_ID
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_FACEBOOK_PARSER_APP_ID
                  key: latest
            - name: FACEBOOK_PARSER_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_FACEBOOK_PARSER_APP_SECRET
                  key: latest
            - name: FB_SESSION_COOKIES
              valueFrom:
                secretKeyRef:
                  name: fb-session-cookies
                  key: latest
            
            # AI/ML API Keys (Secrets)
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_GEMINI_API_KEY
                  key: latest
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_OPENAI_API_KEY
                  key: latest
            
            # Stripe Credentials (Secrets)
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_STRIPE_SECRET_KEY
                  key: latest
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_STRIPE_PUBLISHABLE_KEY
                  key: latest
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_STRIPE_WEBHOOK_SECRET
                  key: latest
            - name: STRIPE_DJ_SUBSCRIPTION_PRICE_ID
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_STRIPE_DJ_SUBSCRIPTION_PRICE_ID
                  key: latest
            - name: STRIPE_DJ_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: KARAOKE_HUB_STRIPE_DJ_WEBHOOK_SECRET
                  key: latest
            # Ollama configuration (disabled in Cloud Run by default)
            # Uncomment and set these if you deploy a separate Ollama service:
            # - name: ENABLE_OLLAMA
            #   value: "true"
            # - name: OLLAMA_HOST
            #   value: "https://your-ollama-service-url"
            # - name: OLLAMA_MODEL
            #   value: "deepseek-r1:8b"
