# Cloud Build configuration for KaraokeHub
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub:latest'
      - '-t'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub:$BUILD_ID'
      - '--file'
      - 'Dockerfile'
      - '.'
    timeout: '1200s'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'karaokehub'
      - '--image'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--cpu-throttling'
      - '--concurrency'
      - '80'
      - '--add-cloudsql-instances'
      - 'heroic-footing-460117-k8:us-central1:accountant'
      - '--set-env-vars'
      - 'NODE_ENV=production,FRONTEND_URL=https://karaoke-hub.com,BACKEND_URL=https://karaoke-hub.com,ALLOWED_ORIGINS=https://karaoke-hub.com,DATABASE_SOCKET_PATH=/cloudsql/heroic-footing-460117-k8:us-central1:accountant,DATABASE_NAME=karaoke-hub,DATABASE_SYNCHRONIZE=false,INSTANCE_CONNECTION_NAME=heroic-footing-460117-k8:us-central1:accountant,STRIPE_AD_FREE_PRICE_ID=price_ad_free_monthly,STRIPE_PREMIUM_PRICE_ID=price_premium_monthly,PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser,PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true,PRODUCTION_UPLOAD_TOKEN=karaoke-hub-data-integration-system'
      - '--update-secrets'
      - 'DATABASE_USERNAME=KARAOKE_HUB_DB_USERNAME:latest,DATABASE_PASSWORD=KARAOKE_HUB_DB_PASSWORD:latest,JWT_SECRET=KARAOKE_HUB_JWT_SECRET:latest,GOOGLE_CLIENT_ID=KARAOKE_HUB_GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=KARAOKE_HUB_GOOGLE_CLIENT_SECRET:latest,GEMINI_API_KEY=KARAOKE_HUB_GEMINI_API_KEY:latest,GOOGLE_MAPS_API_KEY=KARAOKE_HUB_GOOGLE_MAPS_API_KEY:latest,STRIPE_SECRET_KEY=KARAOKE_HUB_STRIPE_SECRET_KEY:latest,STRIPE_PUBLISHABLE_KEY=KARAOKE_HUB_STRIPE_PUBLISHABLE_KEY:latest,STRIPE_WEBHOOK_SECRET=KARAOKE_HUB_STRIPE_WEBHOOK_SECRET:latest'

# Store images in Container Registry
images:
  - 'gcr.io/heroic-footing-460117-k8/karaokehub:latest'
  - 'gcr.io/heroic-footing-460117-k8/karaokehub:$BUILD_ID'

# Build timeout
timeout: '1800s'
