# Cloud Build configuration for KaraokeHub
steps:
  # Step 1: Build the Docker image with Google Maps API key
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub:latest'
      - '-t'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub:$BUILD_ID'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_API_KEY=$$GOOGLE_MAPS_API_KEY'
      - '--file'
      - 'Dockerfile'
      - '.'
    timeout: '1200s'
    secretEnv: ['GOOGLE_MAPS_API_KEY']

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'karaokehub'
      - '--image'
      - 'gcr.io/heroic-footing-460117-k8/karaokehub:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--cpu-throttling'
      - '--concurrency'
      - '80'
      - '--add-cloudsql-instances'
      - 'heroic-footing-460117-k8:us-central1:accountant'
      - '--set-env-vars'
      - 'NODE_ENV=production,FRONTEND_URL=https://karaokehub-203453576607.us-central1.run.app,DATABASE_HOST=localhost,DATABASE_PORT=3306,DATABASE_NAME=karaoke-hub,DATABASE_SYNCHRONIZE=false,INSTANCE_CONNECTION_NAME=heroic-footing-460117-k8:us-central1:accountant'
      - '--update-secrets'
      - 'DATABASE_USERNAME=KARAOKE_HUB_DB_USERNAME:latest,DATABASE_PASSWORD=KARAOKE_HUB_DB_PASSWORD:latest,JWT_SECRET=KARAOKE_HUB_JWT_SECRET:latest,GOOGLE_CLIENT_ID=KARAOKE_HUB_GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=KARAOKE_HUB_GOOGLE_CLIENT_SECRET:latest,GEMINI_API_KEY=KARAOKE_HUB_GEMINI_API_KEY:latest'

# Store images in Container Registry
images:
  - 'gcr.io/heroic-footing-460117-k8/karaokehub:latest'
  - 'gcr.io/heroic-footing-460117-k8/karaokehub:$BUILD_ID'

# Build timeout
timeout: '1800s'

# Available secrets for build steps
availableSecrets:
  secretManager:
  - versionName: projects/heroic-footing-460117-k8/secrets/KARAOKE_HUB_GOOGLE_MAPS_API_KEY/versions/latest
    env: 'GOOGLE_MAPS_API_KEY'
