version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: karaoke-hub
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    restart: always
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: karaoke-hub
      DATABASE_SYNCHRONIZE: 'true'
      JWT_SECRET: production-jwt-secret-change-this
      PORT: 3001
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
