#!/bin/bash

# OAuth Provider Setup Script
# This script provides the exact URLs you need to configure in your OAuth providers

echo "=================================================="
echo "           OAUTH PROVIDER SETUP GUIDE"
echo "=================================================="
echo ""

echo "🔧 GOOGLE CLOUD CONSOLE SETUP"
echo "URL: https://console.cloud.google.com/apis/credentials"
echo ""
echo "1. Authorized redirect URIs (add both):"
echo "   http://localhost:8000/api/auth/google/callback"
echo "   https://karaoke-hub.com/api/auth/google/callback"
echo ""
echo "2. Authorized JavaScript origins (OPTIONAL - not needed for your server-side flow):"
echo "   Only add these if you plan to use client-side OAuth libraries:"
echo "   http://localhost:5173"
echo "   http://localhost:8000"
echo "   https://karaoke-hub.com"
echo "   https://karaoke-hub.com"
echo ""

echo "🔧 FACEBOOK DEVELOPER CONSOLE SETUP"
echo "URL: https://developers.facebook.com/apps/"
echo ""
echo "1. Facebook Login > Settings > Valid OAuth Redirect URIs:"
echo "   http://localhost:8000/api/auth/facebook/callback"
echo "   https://karaoke-hub.com/api/auth/facebook/callback"
echo ""
echo "2. App Domains:"
echo "   localhost"
echo "   karaoke-hub.com"
echo "   karaoke-hub.com"
echo ""
echo "3. Site URL:"
echo "   Development: http://localhost:5173"
echo "   Production: https://karaoke-hub.com"
echo ""

echo "🧪 TESTING YOUR SETUP"
echo ""
echo "Local Development:"
echo "1. Start backend: npm run dev"
echo "2. Start frontend: cd client && npm run dev"
echo "3. Visit: http://localhost:5173"
echo "4. Test OAuth login buttons"
echo ""
echo "Production:"
echo "1. Visit: https://karaoke-hub.com"
echo "2. Test OAuth login buttons"
echo ""

echo "🐛 COMMON ISSUES"
echo ""
echo "❌ redirect_uri_mismatch:"
echo "   - Check URLs exactly match (no extra slashes, correct protocol)"
echo "   - Verify you're testing the right environment"
echo ""
echo "❌ CORS errors:"
echo "   - Ensure JavaScript origins are configured"
echo "   - Check browser console for specific CORS errors"
echo ""
echo "❌ OAuth provider not found:"
echo "   - Verify environment variables are set"
echo "   - Check backend logs for credential errors"
echo ""

echo "✅ QUICK VERIFICATION"
echo ""
echo "Check if OAuth endpoints are accessible:"
echo "curl http://localhost:8000/api/auth/google"
echo "curl http://localhost:8000/api/auth/facebook"
echo ""

echo "=================================================="
echo "Save this output and use it to configure your OAuth providers!"
echo "=================================================="
